require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"

Rails/NegateInclude:
  Enabled: false

# `uniqueness: %i[tenant_id]` のような複合 uniq に対応していないので無効にする。
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "config/**/*.rb"

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
